[package]
name = "trill_script"
version = "0.1.0"
edition = "2024"

[dependencies]
trill_core = { path = "../trill_core" }

logos.workspace = true
ustr.workspace = true
codespan-reporting.workspace = true

[dev-dependencies]
rand.workspace = true

