[package]
name = "bevy_trill_demo"
version = "0.1.0"
edition = "2024"

[dependencies]
bevy = "0.17.2" 
bevy_trill = { path = "../crates/bevy_trill" }
bevy_mod_props = { path = "../crates/bevy_mod_props" }
