[package]
name = "trill_core"
version = "0.1.0"
edition = "2024"

[dependencies]
bevy_mod_props = { path = "../bevy_mod_props", default-feature = false }

itertools.workspace = true
rand.workspace = true
rapidhash.workspace = true
ustr.workspace = true
